### ISSUE TITLE
Country and State Not Visible in Admin Panel

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#1]
In FTO control panel , country and state is not visible..

http://www.fintipoffers.com/ControlPanel/Admin/AdminControlPanelPage.aspx

Country and state should not be visible in default.aspx once it is set .. But it should be visible in admin control panel.. There is already a method which will make it visible or non visible .. Call it form outside the control based on the data in the cookee ..

**Comment by jithinmohanan** [comment]
Issue is fixed by removing the hiding function in admin control panel

**Comment by thomastom99** [comment]
Did you uploaded the fix?. It is not reflecting it in my admin control panel.  Also there is no need to show the Category in "Admin Control Panel". So Please hide it ..
