### ISSUE TITLE
Please arrange offer Ads in Respective Shop Folders

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#11]
Please arrange offer Ads in Respective Shop Folders in the coming relase. Please note that shop folder name should not contain spaces. If Shop name contains spaces it should be replaced by underscore "_" . Also all special characters should be removed. Also The shop folder name should be in small letters..

Please create  a method in Utility class like

static string GetShopFolderName(string shopID, string strOrganizationName )  

So that it can be called form anywhere..
It will be better to append the shop id along with the name as there ca be same shop names in diffrent places. 

So if the Shop name is KTS InfoTech Pvt. LTD. and id is 123 then the folder name will be

kts_infotech_pvt_ltd_123

Hope things are clear..

**Comment by jithinmohanan** [comment]
Now each shop has its own folder for ads and logo images
