### ISSUE TITLE
Problems in Location and Category

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#113]
1. Create Town form District is not working all the Time. For exam if a town is exists for a district, then if we didnt select a district and clicked "Create Town form District " , it will not create other towns. Please test it everything in full..
2. Also if we didnt select the state and if "Create Town form District" is clicked, then it should create town for all state/district in the country. This might be usefull when we enter town details for other countries as we don't have much info regarding towns.
3. There should be a provision to edit the existing category names. Currently I am changing form the Backed..
4. There is a spelling the spelling for Shop/Business Category is wrong an "r" is missing in  http://www.fintipoffers.com/register.aspx

**Comment by midhunraj500** [comment]
fixed the issue

**Comment by Elizabeth-teena** [comment]
Fixed the issue
