### ISSUE TITLE
Implement ShopInfo.aspx

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#12]
A. Search Shops 
1. Shop Name Radio Button
2. Town Radio Buttom
3. District Radio Button
4. Category (Optional)
5. Search Button
6. The Seach Results should be displayed in Search Results User Control 
6.1 Add Methods in the user Control
6.2 Place a Grid View in the User Control
# 

Display All Shops ,
Country Wise,
State Wise,
Dist Wise,
Town Wise based on Navigation Query String.
All Shops URL will be displayed as http://www.fintipoffers.com/shops/CommonUtils.GetShopFolderName(string shopID, string strOrganizationName).aspx
Features
1. resposive design Using Bootstrap
2. On Top Search Shops with a Search Edit Box and Button . The Results will be displayed in Search Results User Control UserControl/SearchResultsControl

3.When you Directly Navigate to http://www.fintipoffer.com/ShopInfo.aspx , it will display the search edit box and button and below that all country Names (with at least one shop) with link like http://www.fintipoffer.com/ShopInfo.aspx?country_id=231
4. When you navigate to the country link , it should display all states (with at least one shop) with link like http://www.fintipoffer.com/ShopInfo.aspx?state_id=231
5. When you Navigate to the Sate Link , it should display all Districts (with at least one shop) with link like http://www.fintipoffer.com/ShopInfo.aspx?dist_id=231
6. When you Navigate to the District Link , it should display all Towns (with at least one shop) with link like http://www.fintipoffer.com/ShopInfo.aspx?town_id=231
7. When you click on the Town, it should display all shops basic Info with the URL like http://www.fintipoffers.com/shop/kts_infotech_pala_453.aspx . This will be an alias URL which willpoint inernallly like http://www.fintipoffer.com/ShopInfo.aspx?shop_id=453 . The aliasing technique is already done in WebCloud and you can see what is done in session_start in webcloud software

Created Skeleton User Controls : ShopInfoControl.ascx, SearchResultsControl.ascx

Please note : when you develop code ShopInfo.aspx URL will be the http://base_url/ShopInfo.aspx . The base URL code info is already there in fintipoffers source and also availabel in webcloud.

**Comment by thomastom99** [comment]
[PM 01:27:04] Tom Thomas: Also make the ShopInfo.aspx design similar to Default.aspx design
[PM 01:27:21] Tom Thomas: I mean the Blue Compartments in Default.aspx
[PM 01:27:27] Tom Thomas: design style
[PM 01:27:54] Tom Thomas: search box is in one Blue compartment
[PM 01:28:02] Tom Thomas: and the rest is in the other Compartment
[PM 01:28:21] Tom Thomas: In short it should look Professional
[PM 01:28:28] Tom Thomas: 
[PM 01:30:03] Tom Thomas: I belive we can show in the ShopInfo cntrol an option to show all active offers and show In Active Offers (needs to discuss) like an expandable/collapsible option similar to Shop Control Panel

**Comment by thomastom99** [comment]
By Default in the Shop Info Page , the active offers should be diaplyed. Now in the www.finitipoffers.com website , it is not expanded by default, but it is in the collapsed state. Please change it if you didnt changed it in the latest version.

**Comment by manu-mt** [comment]
The active add in the Shop Info Page changed to expand by default.
