### ISSUE TITLE
Beautify ASPX Page

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#16]
Please Beautify the following Pages in user control panel
1.BuyCredits.aspx . Ans also Pl Put it inside User Control Panel folder
2. TransactionCanceled.aspx
3.TransactionFailed.aspx

**Comment by manu-mt** [comment]
Changes..
1. BuyCredits UI changed. Added  a pannel .
2. TransactionCanceled page added to shop owner master page.. also added a canceled message.
3. TransactionFailed page added to shop owner master page.. also added a message.
