### ISSUE TITLE
Unwanted Edit Box in Suggest a Category

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#17]
Unwanted Edit Box Suggest a Location/Category Group.

I mean suggest a category edit box is unwanted. Only the sentence with Hyperlink to Contact Us is goo enough (if possible with Query string in ContactUs.aspx with Name, E mail etc for faster form filling if the user already signed in ).

**Comment by thomastom99** [comment]
Sorry Some Confusion. When I enter text in edit bod and then clicks Contact us form automatically fills. So the Link (Suggest new Category ) should be towards the bottom.

**Comment by thomastom99** [comment]
This should be the sentence..

We feel that we have already added almost all the general categories which a customer is looking for. This means that a shop owner can place his offer ad on any of this nearest categories. However if you feel that we have missed any of the category Please click on the link below after entering your category on the above text box. For now you can Place the ad to the nearest category till further information.
Suggest new Category

**Comment by jithinmohanan** [comment]
Message changed
