### ISSUE TITLE
Logo and Image Width and Height Caption

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#19]
When you upload Logo or Offer Image , you need to display the Prefred Width and Height after getting the settings form the Application Object like

Upload Logo (Preferred Size: 80X80 Pixels)
Upload Image (Preferred ize : 300X300 Pixels)

Please do it everywhere the file upload operation is happening.

**Comment by jithinmohanan** [comment]
set notification message for all upload image button: from settings
