### ISSUE TITLE
Preference Page is Crashing

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#2]
Click Preference Page and it is crashing..

http://www.fintipoffers.com/ClientPreferences.aspx

**Comment by thomastom99** [comment]
This is the crash dump..

Server Error in '/kts/shopoffer' Application.
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[NullReferenceException: Object reference not set to an instance of an object.]
   ShopOffer.ClientPreferences.ManageSelection() +926
   ShopOffer.ClientPreferences.Page_Load(Object sender, EventArgs e) +40
   System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e) +14
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +35
   System.Web.UI.Control.OnLoad(EventArgs e) +99
   System.Web.UI.Control.LoadRecursive() +50
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +627

**Comment by thomastom99** [comment]
Jithin I got it right now
[PM 11:32:17] Tom Thomas: we need to put inside the new statement inside the page load..
[PM 11:32:24] Tom Thomas: see what I did below..
[PM 11:33:55] Tom Thomas: public partial class ClientPreferences : FtoBasePage
    {

```
    SettingsManagementBll m_objsettingsManagementBll ;
    ShopOwnerManagementBll m_ShopOwnerManagementBll;
    OfferAdManagementBll objOfferAdManagementBll ;
    AdminManagementBll objAdminManagementBll ;

    protected void Page_Load(object sender, EventArgs e)
    {
        try
        {
            m_objsettingsManagementBll = new SettingsManagementBll();
            m_ShopOwnerManagementBll = new ShopOwnerManagementBll();
            objOfferAdManagementBll = new OfferAdManagementBll();
            objAdminManagementBll = new AdminManagementBll();
```

**Comment by jithinmohanan** [comment]
Hi Sir,

The problem which was generated due to the modification of database. I have fixed the issue.

**Comment by jithinmohanan** [comment]
There are 3 methods which has been used for binding data by creating a custom Dataset from application object. There is a mismatch of number of columns in the application object and custom dataset after adding the new reserved fields into the database.

**Comment by thomastom99** [comment]
This is the reasn why I asked you to put Reserverd filed at a much earlier time so that we can detect it at a much earlier time..

**Comment by thomastom99** [comment]
OK I will check it and will let you know.. Please take a backup of the database if all the settings are fine..

Also please make sure that you declared and initialized the variable in the page_load like the one below..

```
   public partial class ClientPreferences : FtoBasePage
{
```

//Declare the member variable like this
        SettingsManagementBll m_objsettingsManagementBll ;
        ShopOwnerManagementBll m_ShopOwnerManagementBll;
        OfferAdManagementBll objOfferAdManagementBll ;
       AdminManagementBll objAdminManagementBll ;

```
    protected void Page_Load(object sender, EventArgs e)
    {
        try
        {
```

//Initialize the member variable in page load
                m_objsettingsManagementBll = new SettingsManagementBll();
                m_ShopOwnerManagementBll = new ShopOwnerManagementBll();
                objOfferAdManagementBll = new OfferAdManagementBll();
                objAdminManagementBll = new AdminManagementBll();

This is the best approach to do it.. Please modify all areas in the code wherever this is applicable..
