### ISSUE TITLE
Shop Owner CP Modification

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#34]
Please modify show owner CP like the one below..
1. Logo and Caption display siliar to ShopInfo.aspx shop page .. ie Logo and Title in the Middle.
2. Make Ad Category combo box width the same as other edit box width.

**Comment by thomastom99** [comment]
see how the Shop logo and Title aligns in this page as an example..
http://www.fintipoffers.com/shop/Adams_Shop_8.aspx

**Comment by manu-mt** [comment]
1.The alignment of logo and shop name now same as shopinfo.aspx page
2. Ad Category combo box width now same as he edit boxes
