### ISSUE TITLE
Offer ad Search problem

### ISSUE THREAD

**Issue by jithinmohanan** [thomastom99/fto#35]
offer search result not working

**Comment by thomastom99** [comment]
What is the Problem you reported..?

**Comment by jithinmohanan** [comment]
yesterday Rajeev reported one problem in the search results of ads from control panel and offer search result from Home page. Miss mach of some results.

**Comment by thomastom99** [comment]
Please make sure all search resulats are sorted according to the latest offers (sort by ID and date in addition to category and location)

**Comment by jithinmohanan** [comment]
ok sir

**Comment by jithinmohanan** [comment]
Search problem Fixed: Changed query to select ads by category.
and Moved the method from  SettingsManagementBll.cs to offeradmanagementBll

Old GetAllAdsListUnder(string strTownID, string strDistID)
new GetAllAdsListUnder(string strTownID, string strDistID,string strCategoryID)
