### ISSUE TITLE
Blue Border for Post offer and Shop Owner Control Panel

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#37]
The Blue Border Should be there similar to serach page for both Post offer as well as Shop Owner control panel page.

**Comment by thomastom99** [comment]
Blue Border for register.aspx , cancel payment, error page and other pages too..

**Comment by manu-mt** [comment]
blue border added to register.aspx , cancel payment, Buycredits,Termsof use and all user pages.
