### ISSUE TITLE
Add Registration Request Date and Regsitration Confirmation Date

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#38]
Add Registration Request Date and Registration Confirmation Date/Shop Owner Creation date as a separate filed in the table.

**Comment by thomastom99** [comment]
Display Registration Request Logs in the log Page as a Combo box Item (Rajeev). 

In the User Control Panel , Display a Filed like "Registered on  :XXXX" (Manu)

**Comment by jithinmohanan** [comment]
registration requested date and registration completed date saved to database : registration_info

**Comment by jithinmohanan** [comment]
Registration request date and Registration completed date saved to registration_info.
Also updated the Date of shop Owner added into shop_master (reg_completed_date)
