### ISSUE TITLE
New Log Table

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#39]
Regarding log file saving, in addition to Saving Logs to the File , there should be an option to put the Logs in the table to display it easily form DeviceStatistics.aspx page form Control Panel. 
Rajeev is also working on the delete all log data from the table so that Log Table size may may not be an issue. 

I believe we can do the insertion to the table form one common function.

**Comment by jithinmohanan** [comment]
Log to Database: new Table logs_info added with fields : 
user_type var45
log_type  var45
operation  var45
operation_time  var45
logs_msg longtext

Method implemented for insertion of data. Now tracking the process such as Shop (Add,Edit,Delete), OfferAd(Add,Edit,Delete)
