### ISSUE TITLE
If Town not selected the Offer will not display in Mobile App as well as Website

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#42]
If Town not selected the Offer will not display in Mobile App as well as Website http://www.fintipoffers.in  .It was working previously even if the district is selected. Something to do with query. Pl Check..

**Comment by thomastom99** [comment]
I think the problem is happening when you are selecting only District and not selecting town as well as category .. pl check

**Comment by jithinmohanan** [comment]
Fixed: By adding a single quote after district id in where condition.

**Comment by thomastom99** [comment]
Fixed
