### ISSUE TITLE
Test fintipoffers in different web browsers like Mozilla firefox,Google chrome,Microsoft Edge,Interenet Explorer,Apple Safari and Oprea 

### ISSUE THREAD

**Issue by rajeev-kk** [thomastom99/fto#60]
Test fintipoffers in different web browsers and make an excel sheet

**Comment by Elizabeth-teena** [comment]
when we create new account through mailed link, we are back to the 'ShopOwnerSettingsPage' through the back button in the browser even after we logged out

**Comment by Elizabeth-teena** [comment]
when we create new account through mailed link, we are back to the 'ShopOwnerSettingsPage' through the back button in the browser even after we logged out

**Comment by thomastom99** [comment]
Will implement it in the next major release
