### ISSUE TITLE
Beautify Download FAQ and Terms Of Use 

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#85]
Beautify Download FAQ and Terms Of Use  with class 
class="panel-heading" similar to "Welcome to FinTipOffers" Look

Heading 
1. Download FinTipOffers Application
2. FinTipOffers Frequently Asked Questions
3. FinTipOffers Terms Of Use

**Comment by thomastom99** [comment]
Didnt do class="panel-heading" for Terms of Use ..

**Comment by manu-mt** [comment]
fixed
