### ISSUE TITLE
Contact us content was not loading again 

### ISSUE THREAD

**Issue by thomastom99** [thomastom99/fto#96]
Contact us content was not loading again when you login to admin panel after saving the contactus contents.

**Comment by DaduThomas** [comment]
When a user contacted through contact us form, it will show in admin's mail.

**Comment by thomastom99** [comment]
I am mentioning about the Admin Control Panel Contact us editor Address contents.
1. Please login as Admin. 
2 Go to contact us HTML Editor. Enter contents . 
3. Save it and Log off. 
Then login again to Admin CP and Go to Contact us editor. 
You can see no contents or few contents like KTS InfoTech PVT LTD.

**Comment by thomastom99** [comment]
see this
![contactus](https://cloud.githubusercontent.com/assets/7078341/15960308/da0b7116-2f1c-11e6-922e-5cf8c8cbaaee.png)

**Comment by DaduThomas** [comment]
yes sir, i have checked. there is a problem in editor.

**Comment by thomastom99** [comment]
It may not be loading the data gain.. Check how other variable is loading in the editor from  the data structure.. Discuss with Jithin or Rajeev if needed before you fix.. Show them the bug fist ..

**Comment by DaduThomas** [comment]
ok sir.

**Comment by thomastom99** [comment]
I Fixed it for Myself. I will update the source soon.

**Comment by thomastom99** [comment]
Just test it again locally and close this bug.
